# Generated by Django 2.2.2 on 2019-07-02 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Nome')),
                ('actual_quantity', models.IntegerField(verbose_name='quantidade atual')),
                ('material', models.CharField(max_length=300, verbose_name='material')),
                ('capacity', models.CharField(max_length=300, verbose_name='capacidade/comprimento')),
                ('location', models.CharField(max_length=300, verbose_name='localização')),
                ('brand', models.CharField(max_length=300, verbose_name='marca')),
                ('obs', models.TextField(verbose_name='observações')),
                ('reference', models.CharField(max_length=300, verbose_name='referência')),
                ('min_limit', models.IntegerField(verbose_name='limite mínimo')),
            ],
            options={
                'verbose_name': 'Produto',
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='quantidade')),
                ('movement_type', models.IntegerField(choices=[(0, 'Saída'), (1, 'Entrada')], default=0, verbose_name='tipo de movimento')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Product', verbose_name='produto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='utilizador')),
            ],
            options={
                'verbose_name': 'Movimentação',
            },
        ),
    ]
