# Generated by Django 2.2.2 on 2019-07-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='actual_quantity',
            field=models.IntegerField(default=12, verbose_name='quantidade atual'),
            preserve_default=False,
        ),
    ]
