# Generated by Django 2.2.2 on 2019-07-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_actual_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.IntegerField(choices=[(0, 'Nenhum'), (1, 'L'), (2, 'Kg'), (3, 'm')], default=0, verbose_name='unidade'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='movement_type',
            field=models.IntegerField(choices=[(0, 'Saída'), (1, 'Entrada')], default=0, verbose_name='tipo de movimento'),
        ),
    ]
