# Generated by Django 2.2.2 on 2019-07-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20190701_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'L'), (2, 'Kg'), (3, 'm')], default=0, verbose_name='unidade'),
        ),
    ]
